### PR TITLE
Move to latest 2.5.4 version, make the install script nicer

### PR DESCRIPTION
**Pull request by tylert**

### CODE REVIEW

**Comment by tylert** [comment]
@westonsteimel

**Comment by tylert** [comment]
@westonsteimel ?

**Comment by westonsteimel** [comment]
Please leave the master and stable directories intact.  Right now the Dockerfiles may be the same; however, the dependencies may diverge in the future.  Also, all of my GitHub Actions across all of my docker repos depend on having that structure

**Comment by tylert** [comment]
Wilco.  Understood.  Expect update soon.

**Comment by tylert** [comment]
I think I put things back the way they were before and corrected the install script.

```
KEEPASSXC_VARIANT=master KEEPASSXC_VERSION=master ./install.sh  # build 'master' HEAD from master/Dockerfile
...
KEEPASSXC_VARIANT=stable KEEPASSXC_VERSION=2.5.4 ./install.sh  # build '2.5.4' tag from stable/Dockerfile
```

**Pull request merged**
